-- Table "Competition Participant"
CREATE TABLE COMP_PART (
  CompFK NUMBER(10) NOT NULL,
  PartFK NUMBER(10) NOT NULL
) TABLESPACE competitions;

ALTER TABLE SPONSOR
  ADD (
  CONSTRAINT comp_fk FOREIGN KEY (CompFK) REFERENCES COMP (CompPK),
  CONSTRAINT part_fk FOREIGN KEY (PartFK) REFERENCES PART (PartPK),
  CONSTRAINT comp_part_pk PRIMARY KEY (CompFK, PartFK)
  );