ALTER TABLE COMP
  ADD (
  CONSTRAINT comp_orgteam_fk FOREIGN KEY (OrgTeamFK) REFERENCES ORG_TEAM (OrgTeamPK),
  CONSTRAINT compcountry_fk FOREIGN KEY (CountryFK) REFERENCES COUNTRY (CountryPK),
  CONSTRAINT comp_comptype_fk FOREIGN KEY (CompTypeFK) REFERENCES COMP_TYPE (CompTypePK)
  );

ALTER TABLE COMP_PART
  ADD (
  CONSTRAINT comp_part_comp_fk FOREIGN KEY (CompFK) REFERENCES COMP (CompPK),
  CONSTRAINT comp_part_part_fk FOREIGN KEY (PartFK) REFERENCES PART (PartPK),
  CONSTRAINT comp_part_pk PRIMARY KEY (CompFK, PartFK)
  );

ALTER TABLE EQUIP
  ADD (
  CONSTRAINT equip_type_fk FOREIGN KEY (TypeFK) REFERENCES EQUIP_TYPE (EquipTypePK),
  CONSTRAINT equip_owner_fk FOREIGN KEY (OwnerFK) REFERENCES ORG (OrgPK)
  );

ALTER TABLE ORG
  ADD (
  CONSTRAINT org_country_fk FOREIGN KEY (CountryFK) REFERENCES COUNTRY (CountryPK),
  CONSTRAINT org_org_team_fk FOREIGN KEY (OrgTeamFK) REFERENCES ORG_TEAM (OrgTeamPK)
  );

ALTER TABLE PART
  ADD (
  CONSTRAINT part_country_fk FOREIGN KEY (CountryFK) REFERENCES COUNTRY (CountryPK),
  CONSTRAINT part_comp_fk FOREIGN KEY (CompFK) REFERENCES COMP (CompPK),
  CONSTRAINT part_image_fk FOREIGN KEY (ImageFK) REFERENCES AVATAR (AvatarPK)
  );

ALTER TABLE PRIZE
  ADD (
  CONSTRAINT prize_type_fk FOREIGN KEY (TypeFK) REFERENCES PRIZE_TYPE (PrizeTypePK),
  CONSTRAINT prize_winner_fk FOREIGN KEY (WinnerFK) REFERENCES PART (PartPK),
  CONSTRAINT prize_comp_fk FOREIGN KEY (CompFK) REFERENCES COMP (CompPK)
  );

ALTER TABLE SPONSOR
  ADD (
  CONSTRAINT sponsor_country_fk FOREIGN KEY (CountryFK) REFERENCES COUNTRY (CountryPK),
  CONSTRAINT sponsor_comp_fk FOREIGN KEY (CompFK) REFERENCES COMP (CompPK),
  CONSTRAINT sponsor_consponsortype_fk FOREIGN KEY (SponsorTypeFK) REFERENCES SPONSOR_TYPE (SponsorTypePK)
  );
