DEFINE username='';
DEFINE tablespacename='';

-- DELETE USER
DROP user &&username CASCADE;
-- DELETE TABLESPACE
DROP TABLESPACE &&tablespacename INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
